api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "hide-cod"
type = "function"
uid = "92646719-3161-8267-b6b4-b6eff9f336009a816961"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/hide-cod"
  details = "/app/hide-cod"
